#!/usr/bin/env python3

import os
import sys


def parse_pattern(pat_string):
    letters = ""
    values = [0]
    pos = 0
    for ch in pat_string:
        if ch.isdigit():
            values[pos] = int(ch)
        elif ch.isalpha() or ch == ".":
            letters += ch
            pos += 1
            values.append(0)
        else:
            # Invalid character, skip this pattern
            print(f"Invalid char '{ch}' (ord {ord(ch)}) in line: {pat_string}")
            return None, None
    return letters, values


def escape_c_string(s):
    r"""Return a C string literal content where non-ASCII bytes are escaped as
    three-digit octal escapes (e.g. \303) to ensure the generated header
    remains ASCII and that escapes are never ambiguous to the C/C++ parser."""
    b = s.encode("utf-8")
    parts = []
    for byte in b:
        if byte == 34:  # double quote
            parts.append('\\"')
        elif byte == 92:  # backslash
            parts.append("\\\\")
        elif 32 <= byte <= 126:
            parts.append(chr(byte))
        else:
            parts.append("\\%03o" % byte)
    return "".join(parts)


def generate_header(pattern_file, header_file, define_name, lang_name, raw=False):
    patterns = []
    # Read pattern files as UTF-8 so multibyte characters become single
    # Unicode codepoints (e.g. 'ä'). When emitting byte arrays we encode
    # those codepoints to Latin-1 so characters map to a single byte value
    # (0xE4 for 'ä'), which keeps values and letter counts aligned.
    with open(pattern_file, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                letters, values = parse_pattern(line)
                if letters is not None:
                    patterns.append((letters, values))

    # Sort patterns by the UTF-8 byte sequence so the generated byte arrays
    # are in the same lexicographic order the runtime uses (byte-wise).
    patterns.sort(key=lambda x: x[0].encode("utf-8"))

    # Generate a flash-friendly C header with const char* and uint8_t arrays
    out_file = header_file
    with open(out_file, "w", encoding="utf-8") as f:
        f.write(f"#ifndef {define_name}\n")
        f.write(f"#define {define_name}\n")
        f.write("\n")
        f.write('#include "hyphenation_patterns.h"\n')
        f.write("\n")
        f.write("// Generated pattern storage suitable for embedding in flash.\n")
        f.write(
            "// Non-ASCII characters are escaped as octal \ooo sequences to keep the header ASCII and\n"
        )
        f.write("// portable across toolchains.\n")
        f.write(
            "// Each pattern: a null-terminated letters string and a uint8_t values array.\n"
        )
        f.write("// Run this script to regenerate with the full pattern set.\n")
        f.write("\n")
        f.write(
            "// Patterns (each pattern: letters array, values array, then PatternC)\n"
        )
        f.write(
            "// Arrays and struct entries are emitted next to each other to improve\n"
        )
        f.write("// readability and data locality.\n")
        f.write("\n")
        # sanitize lang_name for use in identifiers
        prefix = "".join(c if (c.isalnum() or c == "_") else "_" for c in lang_name)
        pats_names = []
        for idx, (letters, values) in enumerate(patterns):
            # letters as UTF-8 byte array
            b = letters.encode("utf-8")
            # expand values (one value per byte boundary)
            expanded = [0] * (len(b) + 1)
            if values and len(values) > 0:
                expanded[0] = values[0]
            cum = 0
            for i, ch in enumerate(letters):
                ch_bytes = ch.encode("utf-8")
                cum += len(ch_bytes)
                if i + 1 < len(values):
                    expanded[cum] = values[i + 1]
            bytes_list = ", ".join(str(byte) for byte in b)
            # emit comment, arrays, and pat on adjacent lines
            f.write(f"// {letters}\n")
            f.write(
                f"static const std::uint8_t {prefix}_let{idx}[] = {{{bytes_list}}};\n"
            )
            f.write(
                f"static const std::uint8_t {prefix}_val{idx}[] = {{{', '.join(map(str, expanded))}}};\n"
            )
            f.write(
                f"static const PatternC {prefix}_pat{idx} = {{ {prefix}_let{idx}, {prefix}_val{idx}, {len(b)}, {len(b)+1} }};\n"
            )
            f.write("\n")
            pats_names.append(f"{prefix}_pat{idx}")
        # emit the patterns[] array that references the per-pattern `patN` objects
        # emit the `patterns` array in a single line for compactness
        patterns_array_name = f"patterns_{prefix}"
        f.write(f"static const PatternC {patterns_array_name}[] = {{ ")
        f.write(", ".join(pats_names))
        f.write(" };\n")
        f.write("\n")
        f.write(
            f"static const size_t patterns_{prefix}_count = sizeof({patterns_array_name}) / sizeof({patterns_array_name}[0]);\n"
        )
        f.write("\n")
        f.write(
            f"static const HyphenationPatterns {prefix}_patterns = {{{patterns_array_name}, patterns_{prefix}_count}};\n"
        )
        f.write("\n")

        # Compute first-character range index.
        # patterns[] is sorted by UTF-8 byte sequence, so entries for each
        # first byte form a contiguous run.
        char_start = [0] * 128
        char_end = [0] * 128
        for i, (letters, _) in enumerate(patterns):
            first = letters.encode("utf-8")[0]
            if first < 128:
                if char_end[first] == 0:
                    char_start[first] = i
                char_end[first] = i + 1

        def fmt128(arr):
            rows = []
            for r in range(8):
                rows.append(", ".join(str(arr[r * 16 + c]) for c in range(16)))
            return ",\n        ".join(rows)

        f.write(f"// First-character range index for {prefix}_patterns.\n")
        f.write(f"static const HyphenationCharIndex {prefix}_char_idx = {{\n")
        f.write(f"    /* start */ {{\n        {fmt128(char_start)}\n    }},\n")
        f.write(f"    /* end   */ {{\n        {fmt128(char_end)}\n    }}\n")
        f.write("};\n")
        f.write("\n")
        f.write(f"#endif // {define_name}\n")


if __name__ == "__main__":
    if len(sys.argv) not in (5, 6):
        print(
            "Usage: python generate_header.py <pattern_file> <header_file> <define_name> <lang_name> [raw]"
        )
        sys.exit(1)
    pattern_file = sys.argv[1]
    header_file = sys.argv[2]
    define_name = sys.argv[3]
    lang_name = sys.argv[4]
    raw = len(sys.argv) == 6 and sys.argv[5] == "raw"
    generate_header(pattern_file, header_file, define_name, lang_name, raw)
