#ifndef HYPHENATION_PATTERNS_H
#define HYPHENATION_PATTERNS_H

#include <cstddef>
#include <cstdint>

struct PatternC {
  const std::uint8_t* letters;
  const std::uint8_t* values;
  std::uint8_t letters_len;
  std::uint8_t values_len;
};

struct HyphenationPatterns {
  const PatternC* patterns;
  size_t count;
};

// First-character range index: patterns are sorted, so all entries starting
// with byte c form a contiguous subrange [start[c], end[c]).
// Generated by generate_header.py alongside each language header.
struct HyphenationCharIndex {
  std::uint16_t start[128];
  std::uint16_t end[128];
};

#endif  // HYPHENATION_PATTERNS_H
